### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Biscuite-wzy** [byemaxx/callCodeml#2]
Hi developer

I had the same problem as described #1.  When I run "python callCodeml.py paml_files  species_tree" , I get partial results, but some sequences always report errors when processed by callCodeml.
I felt strange, when I use "codeml  codeml.ctl" to run the sequence that reports errors in callCodeml, it can produce normal results. So i don't understand why some sequences were report errors in callCodeml.

The detailed error is: TypeError: 'NoneType' object is not subscriptable
 
best
xiang

**Comment by byemaxx** [comment]
I had updated the code, see [ callcodeml2.py](https://github.com/byemaxx/callCodeml)
